config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/',to: 'home#index'
  namespace :admin do
   resources :users
  end

  get'/login',to: 'sessions#new'
  post'/login',to: 'sessions#create'
  delete'/logout',to: 'sessions#destroy'
  root to: 'top#show'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ログイン後にはsessions#new
  #root to: 'posts#index'
  #↑トップ画面に行ったら自動的に投稿一覧に飛ぶ設定。
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
 has_one_attached :image
    
 belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
          uid:      auth.uid,
          provider: auth.provider,
          email:    User.dummy_email(auth),
          password: Devise.friendly_token[0, 20],
          image: auth.info.image,
          name: auth.info.name,
          nickname: auth.info.nickname,
          location: auth.info.location
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
   @users = User.all
  end  
  
  def show
   @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path,notice:"「{@user.name}」"
    else
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path(@user),notice:"ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice:"ユーザー「#{@user.name}」を削除しました。"
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email, :admin, :password, :password_confirmation)
  end
  
  def require_admin
    redirect_to root_path unless current_user.admin?
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    
    def login_required
      # redirect_to login_path unless current_user
    end
    
    private
    
    def current_user
        @current_user ||=User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @q = current_user.posts.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page])
  end

  def show
    @post = current_user.posts.find(params[:id])
  end
 
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    post.update!(post_params)
    redirect_to posts_url, notice:"投稿「#{post.name}」を更新しました。"
  end
  
  def destroy
   post = current_user.posts.find(params[:id])
   post.destroy
   redirect_to posts_url, notice:"投稿「#{post.name}」を削除しました。"
  end  
  
  def create
    post = Post.new(post_params.merge(user_id: current_user.id))
    post.save!
    redirect_to posts_url, notice: "投稿「#{post.name}」を登録しました。"
  end
  
  
  private
  
  def post_params
    params.require(:post).permit(:name, :description, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :login_required
  
  def new
  end
  
 def create
    user = User.find_by(email: session_params[:email])
    
    if user&.authenticate(session_params[:password])
       session[:user_id] = user.id
       redirect_to root_path,notice:'ログインしました。'
    else 
      render :new
    end
    
 end
 
 def destroy
    reset_session
    redirect_to root_path,notice:'ログアウトしました。'
  end
 
 
 private
  def session_params
   params.require(:session).permit(:email,:password)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :login_required
  def show
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message
      
= form_with model: [admin,user],local: true do |f|
  .form-group
    = f.label :name,'名前'
    = f.text_field :name, class]'form-control'
  .form-group
    = f.label :name,'Email'
    = f.text_field :name, class]'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label'do
     =f.check_box :admin,class:form-check-input'
     |管理者権限
  .form-group 
    = f.label :password,'パスワード'
    = f.password_field :password, class:'form-control'
  .form-group 
    = f.label :password_confirmation,'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit'登録する',class:'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
 =link_to'一覧',admin_users_path,class:'nav-link'
 
 
=render partical:'form',locals: {user: @user}

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to'新規登録',new_admin_user_path,class:'btn btn-primary'

.mb-3
table.table.table-hover
 thead.thead-default
  tr
   th= User.human_attribute_name(:name)
   th= User.human_attribute_name(:email)
   th= User.human_attribute_name(:admin)
   th= User.human_attribute_name(:created_at)
   th= User.human_attribute_name(:updated_at)
   th
 tbody
   - @users.each do |user|
     tr 
      td= link_to user.name,[:admin,user]
      td= user.email
      td= user.admin? ? 'あり':'なし'
      td= user.created_at
      td= user.updated_at
      td
        =link_to'編集',edit_admin_user_path(user), class:'btn btn-primary mr-3'
        =link_to'削除',[:admin, user], method: :delete, data: {confirm:'ユーザー「#user.name」を削除します。よろしいですか？'},class:'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  =link_to'一覧',admin_users_path,class:'nav-link'
  
render partical: 'form',locals: {user: @user}

= form_with model: [:admin, @user], local: true do |f|
  .form_group
      = f.label :name, 'Name'
      = f.text_field :name,class: 'form-control'
  .form-group
   = f.label :email, 'Email'
   = f.text_field :email, class:'form-control'
  .form-check
   = f.label :admin,class:'form-check-label'do
     = f.check_box :admin, class:'form-check-input'
     |管理者権限
  .form-group
   = f.label :password, 'PassWord'
   = f.password_field :paaword, class:'form-control'
  .form-roup
   = f.label :password_confirmation,'パスワード（確認）'
   = f.password_field :password_confirmation, class:'form-control'
  = f.submit'登録する',class:'btn btn-primary'

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justfy-content-end
 = link_to'一覧',admin_users_path,class:'nav-link'
table.table.table-hover
 tbody
   tr
     th= User.human_attribute_name(:id)
     td= @user.id
   tr
     th= User.human_attribute_name(:name)
     td= @user.name
   tr
     th= User.human_attribute_name(:email)
     td= @user.email
   tr
     th= User.human_attribute_name(:admin)
     td= @user.admin? ? 'あり': 'なし'
   tr
     th= User.human_attribute_name(:created_at)
     td= @user.created_at
   tr
     th= User.human_attribute_name(:updated_at)
     td= @user.updated_at

app/views/home/index.html.slim
section#top
  .container
    .row
      .col-lg-12.text-center
        h1.section-heading Person_log
        p what kind of he or she
        hr.my-4/
ul
  - if user_signed_in?
    li= current_user.email
    li= current_user.name
    li= current_user.nickname
    li= current_user.image
    li= current_user.location
    li= link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    li= link_to "ログイン", new_user_session_path

section#contact.bg-dark.text-white.section-top
  .container
    .row
      .col-lg-8.mx-auto.text-center
        h2.section-heading お問い合わせ
        hr.my-4/
    .row
      .col-lg-12.mr-auto.text-center
        a data-show-count="false" href="https://twitter.com/share?url=https://www.escola-pro.com&hashtags=[なんだろ]" target="_blank"
          i.fab.fa-twitter.fa-3x.mb-3
          i.fa.fa-envelope-o.fa-3x.mb-3.sr-contact
        p
          a href="https://twitter.com/ichika4561?lang=ja" target="_blank"  person_log 公式アカウント
        p.mb-5 お問い合わせはTwitterのDMからお気軽に！

footer.footer

app/views/layouts/application.html.slim
script src=("https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js")

doctype html
html
  head
    title
      | Person_log
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar.navbar-expand-lg.navbar-light.bg-light
      .navbar-brand Person_log
        
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to'タスク一覧',posts_path,class:'nav-link'
          - if current_user.admin?
          li.nav-item= link_to'ユーザー一覧',admin_users_path,class: 'nav-link'
          li.nav-item= link_to'ログアウト',logout_path,method: :delete,class: 'nav-link'  
        - else
          li.nav-item= link_to'ログイン',login_path,class:'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield
            
        

app/views/posts/_form.html.slim
=form_with model: post, local: true do |f|
  .form-group
   = f.label :name
   = f.text_field :name,class: 'form-control',id:'post_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'post_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil,class: 'btn btn-primary'

app/views/posts/edit.html.slim
h1 投稿画面の編集

.nav.justify-content-end
 = link_to'一覧',posts_path, class: 'nav-link'
 
=form_with model: @post, local:true do |f|
 .form-group
   = f.label :name
   = f.text_field :name, class:'form-control', id:'post_name'
 .form-group
   = f.label :description
   = f.text_area :description, row: 5,class:'form-control', id: 'post_description'
 = f.submit nil,class: 'btn btn-primary'

app/views/posts/index.html.slim
h1 一覧

=search_form_for @q,class: 'mb-5' do |f|
  .form-group.row
    =f.label :name_cont, '名称',class: 'col-sm-2 col-form-label'
    .col-sm-10
      =f.search_field :name_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

=link_to'新規登録',new_post_path,class:'btn btn-primary mb-3'

.mb-3
  = paginate @posts
  = page_entries_info @posts

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th= Post.human_attribute_name(:name)
            th= Post.human_attribute_name(:created_at)
            th
    tbody
      - @posts.each do |post|
       tr
        td= link_to post.name, post
        td= post.created_at
        td
         = link_to '編集', edit_post_path(post), class:'btn btn-primary mr-3'
         = link_to '削除', post, method: :delete, data: { confirm: "投稿「#{post.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/posts/new.html.slim
h1 投稿画面

.nav.d-flex.justify-content-end
  = link_to'一覧',posts_path, class: 'nav-link'


=render partial: 'form', locals: { post: @post }

app/views/posts/show.html.slim
h1 投稿内容の詳細

.nav.justify-content-end
 = link_to'一覧',post_path, class: 'nav-link'
table.table.table-hover
 tbody
  tr
    th= Post.human_attribute_name(:id)
    td= @post.id
  tr
    th= Post.human_attribute_name(:name)
    td= @post.name
  tr
    th= Post.human_attribute_name(:description)
    th= simple_format(h(@post.description),{}, sanitize: false, wrapper_tag:"div")
  tr
    th= Post.human_attribute_name(:image)
    th= image_tag @post.image if @post.image.attached?
  tr
    th= Post.human_attribute_name(:created_at)
    td= @post.created_at
  tr
    th= Post.human_attribute_name(:updated_at)
    td= @post.updated_at
     = link_to '編集',edit_post_path(post), class:'btn btn-primary mr-3'
     = link_to '削除',@post, method: :delete, data: { confirm: "投稿「#{@post.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/top/show.html.slim
section#top
  .container
   .row
    .col-lg-12.text-center
     h1.section-heading Person_log
     p what kind of he or she
     hr.my-4/


section#contact.bg-dark.text-white.section-top
  .container
    .row
      .col-lg-8.mx-auto.text-center
        h2.section-heading お問い合わせ
        hr.my-4/
    .row
      .col-lg-12.mr-auto.text-center
        a data-show-count="false" href="https://twitter.com/share?url=https://www.escola-pro.com&hashtags=[なんだろ]" target="_blank"
          i.fab.fa-twitter.fa-3x.mb-3
          i.fa.fa-envelope-o.fa-3x.mb-3.sr-contact
        p
          a href="https://twitter.com/ichika4561?lang=ja" target="_blank"  person_log 公式アカウント
        p.mb-5 お問い合わせはTwitterのDMからお気軽に！

footer.footer